language: node_js
sudo: false
node_js:
  - "4.0"
before_install:
  - npm update -g npm
  - npm install -g istanbul
  - npm install -g mocha
  - npm install -g coveralls
after_success:
  - npm run cover && npm run coveralls